# Generated by Django 4.0.4 on 2022-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_company', models.CharField(max_length=100)),
                ('average_speed', models.PositiveSmallIntegerField(default=75)),
                ('cities_where_collect_passengers', models.TextField()),
                ('is_express', models.BooleanField(default=False)),
                ('price', models.PositiveSmallIntegerField(default=25)),
            ],
        ),
    ]
